import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { base } from "./base";
import { dark } from "./themes/dark";
import { light } from "./themes/light";
import { BASE_TOKEN_NAMES, THEME_TOKEN_NAMES } from "./types";

const HEADER = `/*
 * GENERATED by @monorepo-template/tokens — do not edit by hand.
 * Edit src/base.ts or src/themes/*.ts, then run \`bun run generate\` here.
 * Light is the default in :root; the .dark class re-declares the color tokens.
 */`;

/**
 * Render the tokens stylesheet. `prefix` is prepended to every custom property
 * name — the template ships `mt-` so these never shadow shadcn's own
 * `--background`/`--primary`/… variables; web-ui/styles.css maps shadcn's names
 * to `var(--mt-…)`.
 */
export function generateCss(prefix = "mt-"): string {
  const declare = (name: string, value: string) => `  --${prefix}${name}: ${value};`;

  const rootLines = [
    ...THEME_TOKEN_NAMES.map((name) => declare(name, light[name])),
    ...BASE_TOKEN_NAMES.map((name) => declare(name, base[name])),
  ];
  const darkLines = THEME_TOKEN_NAMES.map((name) => declare(name, dark[name]));

  return [HEADER, "", ":root {", ...rootLines, "}", "", ".dark {", ...darkLines, "}", ""].join(
    "\n",
  );
}

/**
 * Two stylesheets from one source:
 *   tokens.css          `--mt-*`, for web-ui — shadcn declares its own
 *                       `--background`/`--primary`, so ours must not collide.
 *   tokens.desktop.css  unprefixed, for consumers with no shadcn in the page
 *                       (apps/desktop). Shorter to read and to write by hand.
 */
export const OUTPUTS = [
  { file: "tokens.css", prefix: "mt-" },
  { file: "tokens.desktop.css", prefix: "" },
] as const;

if (import.meta.main) {
  const outDir = fileURLToPath(new URL("../css/", import.meta.url));
  mkdirSync(outDir, { recursive: true });
  for (const { file, prefix } of OUTPUTS) {
    writeFileSync(`${outDir}${file}`, generateCss(prefix));
    console.log(`Wrote css/${file}`);
  }
}
