import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { base } from "./base";
import { dark } from "./themes/dark";
import { light } from "./themes/light";
import { BASE_TOKEN_NAMES, THEME_TOKEN_NAMES } from "./types";

const HEADER = `/*
 * GENERATED by @monorepo-template/tokens — do not edit by hand.
 * Edit src/base.ts or src/themes/*.ts, then run \`bun run generate\` here.
 * Light is the default in :root; the .dark class re-declares the color tokens.
 */`;

/**
 * Render the tokens stylesheet. `prefix` is prepended to every custom property
 * name — the template ships `mt-` so these never shadow shadcn's own
 * `--background`/`--primary`/… variables; web-ui/styles.css maps shadcn's names
 * to `var(--mt-…)`.
 */
export function generateCss(prefix = "mt-"): string {
  const declare = (name: string, value: string) => `  --${prefix}${name}: ${value};`;

  const rootLines = [
    ...THEME_TOKEN_NAMES.map((name) => declare(name, light[name])),
    ...BASE_TOKEN_NAMES.map((name) => declare(name, base[name])),
  ];
  const darkLines = THEME_TOKEN_NAMES.map((name) => declare(name, dark[name]));

  return [HEADER, "", ":root {", ...rootLines, "}", "", ".dark {", ...darkLines, "}", ""].join(
    "\n",
  );
}

if (import.meta.main) {
  const outDir = fileURLToPath(new URL("../css/", import.meta.url));
  mkdirSync(outDir, { recursive: true });
  writeFileSync(`${outDir}tokens.css`, generateCss());
  console.log("Wrote css/tokens.css");
}
