// Generated by tauri-specta from src-tauri/src/bindings.rs. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	todosFindById: (id: string, userId: string) => __TAURI_INVOKE<{
	id: string,
	title: string,
	completed: boolean,
	categoryId: string | null,
	userId: string,
	createdAt: number | null,
	updatedAt: number | null,
} | null>("todos_find_by_id", { id, userId }),
	todosList: (userId: string) => __TAURI_INVOKE<TodoDto[]>("todos_list", { userId }),
	todosListPaginated: (userId: string, limit: number, offset: number) => __TAURI_INVOKE<TodoPage>("todos_list_paginated", { userId, limit, offset }),
	todosCreate: (input: NewTodo) => __TAURI_INVOKE<TodoDto>("todos_create", { input }),
	todosUpdate: (id: string, userId: string, patch: TodoPatch) => __TAURI_INVOKE<{
	id: string,
	title: string,
	completed: boolean,
	categoryId: string | null,
	userId: string,
	createdAt: number | null,
	updatedAt: number | null,
} | null>("todos_update", { id, userId, patch }),
	todosDelete: (id: string, userId: string) => __TAURI_INVOKE<boolean>("todos_delete", { id, userId }),
	settingsGet: () => __TAURI_INVOKE<AppSettings>("settings_get"),
	settingsSetLocale: (locale: Locale) => __TAURI_INVOKE<AppSettings>("settings_set_locale", { locale }),
	settingsSetTheme: (theme: ThemePreference) => __TAURI_INVOKE<AppSettings>("settings_set_theme", { theme }),
};

/** Events */
export const events = {
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
};

/* Types */
export type AppSettings = {
	locale: Locale,
	theme: ThemePreference,
};

/**
 *  `categoryId` has three states in the domain's `UpdateTodo`: absent (keep),
 *  `null` (clear) and a string (set). JSON cannot carry "absent" through a
 *  typed binding, so the patch spells it out.
 */
export type CategoryPatch = { kind: "keep" } | { kind: "set"; value: string | null };

/**
 *  Mirrors `SUPPORTED_LOCALES` in `@monorepo-template/i18n`. The renderer
 *  asserts at compile time that the generated type and the package's `Locale`
 *  agree, so adding a locale there without adding it here fails `check-types`.
 */
export type Locale = "en" | "es";

export type NewTodo = {
	title: string,
	categoryId: string | null,
	userId: string,
};

/**  Emitted to every window whenever settings change, wherever the change came from. */
export type SettingsChanged = AppSettings;

/**  "system" follows the OS; the renderer resolves it through `prefers-color-scheme`. */
export type ThemePreference = "system" | "light" | "dark";

/**
 *  A todo as it crosses the IPC boundary. Timestamps are epoch milliseconds as
 *  `f64`: exact up to 2^53, and a plain `number` in TypeScript rather than the
 *  `bigint` an `i64` would need.
 */
export type TodoDto = {
	id: string,
	title: string,
	completed: boolean,
	categoryId: string | null,
	userId: string,
	createdAt: number | null,
	updatedAt: number | null,
};

export type TodoPage = {
	data: TodoDto[],
	total: number,
};

export type TodoPatch = {
	title: string | null,
	completed: boolean | null,
	category: CategoryPatch,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

