//! The typed IPC contract. Every command the renderer may call and every event
//! it may listen to is registered here, and `src/bindings.ts` is generated from
//! it — regenerate with `bun run bindings` after changing a command signature.

use tauri_specta::{collect_commands, collect_events, Builder, ErrorHandlingMode};

use crate::{settings, todos};

pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            todos::todos_find_by_id,
            todos::todos_list,
            todos::todos_list_paginated,
            todos::todos_create,
            todos::todos_update,
            todos::todos_delete,
            settings::settings_get,
            settings::settings_set_locale,
            settings::settings_set_theme,
        ])
        .events(collect_events![settings::SettingsChanged])
        // A failed command rejects the promise, like any async call — which is
        // what `ITodoRepository` callers expect.
        .error_handling(ErrorHandlingMode::Throw)
}

#[cfg(test)]
mod tests {
    use specta_typescript::Typescript;

    /// Writes `src/bindings.ts`. Run through `bun run bindings`; CI runs it and
    /// fails if the committed file changes.
    #[test]
    fn export_bindings() {
        super::builder()
            .export(
                Typescript::default().header(
                    "// Generated by tauri-specta from src-tauri/src/bindings.rs. Do not edit.\n",
                ),
                "../src/bindings.ts",
            )
            .expect("failed to export TypeScript bindings");
    }
}
