/// <reference types="@types/bun" />
/**
 * Structural tests for the customizer.
 *
 * For each pattern we copy the current working tree into a temp dir, run the
 * customizer non-interactively with `--skip-verify` (so no install/build — this
 * stays fast), and assert the mechanical promises hold:
 *
 *   - the customizer exits 0,
 *   - exactly the expected app directories survive,
 *   - no `@monorepo-template` scope leaks past the rename,
 *   - the root package.json scope is renamed,
 *   - the generated CI points at the pattern's app directory.
 *
 * The expectations here are an INDEPENDENT oracle (hardcoded), not derived from
 * the customizer's own PATTERNS map, so a wrong edit to that map fails a test.
 *
 * The heavier "does the result actually build?" check runs per-pattern in the
 * `customizer-test.yml` workflow, which runs the customizer for real.
 */

import { afterAll, describe, expect, test } from "bun:test";
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

const ROOT = path.resolve(import.meta.dir, "..");
const SCOPE = "@monorepo-template";

// Every top-level app the pristine template ships. Anything not "kept" by a
// case must be gone after customization.
const ALL_APPS = [
  "apps/web-elysia",
  "apps/server-elysia",
  "apps/web-hono",
  "apps/server-hono",
  "apps/fullstack-fn-only",
  "apps/fullstack-fn-and-convex",
  "apps/mobile",
  "apps/mobile-convex",
  "apps/documentation",
  "apps/desktop",
];

interface Case {
  pattern: string;
  mobile: boolean;
  docs: boolean;
  desktop: boolean;
  /** App dirs expected to survive (independent of the customizer's own config). */
  keep: string[];
  /** The app dir the generated CI should build. */
  ciApp: string;
}

const CASES: Case[] = [
  {
    pattern: "client-server-hono",
    mobile: true,
    docs: true,
    desktop: false,
    keep: ["apps/web-hono", "apps/server-hono", "apps/mobile", "apps/documentation"],
    ciApp: "apps/web-hono",
  },
  {
    pattern: "client-server-elysia",
    mobile: false,
    docs: false,
    desktop: false,
    keep: ["apps/web-elysia", "apps/server-elysia"],
    ciApp: "apps/web-elysia",
  },
  {
    pattern: "server-only-hono",
    mobile: false,
    docs: false,
    desktop: false,
    keep: ["apps/server-hono"],
    ciApp: "apps/server-hono",
  },
  {
    pattern: "fullstack-fn-only",
    mobile: true,
    docs: false,
    desktop: false,
    keep: ["apps/fullstack-fn-only", "apps/mobile"],
    ciApp: "apps/fullstack-fn-only",
  },
  {
    pattern: "fullstack-fn-and-convex",
    mobile: true,
    docs: false,
    desktop: false,
    // This pattern pairs with mobile-convex, not the plain mobile app.
    keep: ["apps/fullstack-fn-and-convex", "apps/mobile-convex"],
    ciApp: "apps/fullstack-fn-and-convex",
  },
  {
    // The desktop app as an optional add-on to a web pattern: it must coexist
    // with the web/server apps and rescue the i18n + tokens packages.
    pattern: "client-server-hono",
    mobile: false,
    docs: false,
    desktop: true,
    keep: ["apps/web-hono", "apps/server-hono", "apps/desktop"],
    ciApp: "apps/web-hono",
  },
  {
    // The desktop-only pattern: no server, no web client, no infra-*.
    pattern: "desktop-local-first",
    mobile: false,
    docs: false,
    desktop: true,
    keep: ["apps/desktop"],
    ciApp: "apps/desktop",
  },
];

const tmpDirs: string[] = [];

afterAll(() => {
  for (const dir of tmpDirs) rmSync(dir, { recursive: true, force: true });
});

/** Copy the current working tree (tracked files) into a fresh temp dir. */
function materialize(): string {
  const dir = mkdtempSync(path.join(tmpdir(), "customize-test-"));
  tmpDirs.push(dir);

  const ls = Bun.spawnSync(["git", "-C", ROOT, "ls-files"], { stdout: "pipe" });
  const files = ls.stdout.toString().trim().split("\n").filter(Boolean);

  for (const rel of files) {
    const src = path.join(ROOT, rel);
    if (!existsSync(src)) continue; // deleted-but-tracked file mid-edit
    const dest = path.join(dir, rel);
    mkdirSync(path.dirname(dest), { recursive: true });
    cpSync(src, dest);
  }
  return dir;
}

/** All file contents in `dir`, excluding installer/VCS noise. */
function allFiles(dir: string): string[] {
  const out: string[] = [];
  // bun.lock is tracked but the rename step leaves it alone (it is regenerated by
  // `bun install`, which --skip-verify skips), so it still holds the old scope.
  const skip = new Set([
    "node_modules",
    ".git",
    ".turbo",
    "dist",
    ".output",
    "bun.lock",
    "bun.lockb",
  ]);
  const walk = (d: string) => {
    for (const entry of require("node:fs").readdirSync(d, { withFileTypes: true })) {
      if (skip.has(entry.name)) continue;
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) walk(full);
      else out.push(full);
    }
  };
  walk(dir);
  return out;
}

describe("customizer produces a clean project per pattern", () => {
  for (const c of CASES) {
    test(`${c.pattern}${c.mobile ? " +mobile" : ""}${c.docs ? " +docs" : ""}`, () => {
      const dir = materialize();

      const args = [
        "scripts/customize.ts",
        "--pattern",
        c.pattern,
        c.mobile ? "--mobile" : "--no-mobile",
        c.docs ? "--docs" : "--no-docs",
        c.desktop ? "--desktop" : "--no-desktop",
        "--name",
        "testscope",
        "--yes",
        "--skip-verify",
      ];
      const proc = Bun.spawnSync(["bun", ...args], { cwd: dir, stdout: "pipe", stderr: "pipe" });

      // 1. Exit 0.
      expect(proc.exitCode, proc.stderr.toString() || proc.stdout.toString()).toBe(0);

      // 2. Exactly the expected apps survive.
      for (const app of c.keep) {
        expect(existsSync(path.join(dir, app)), `expected ${app} to be kept`).toBe(true);
      }
      for (const app of ALL_APPS) {
        if (c.keep.includes(app)) continue;
        expect(existsSync(path.join(dir, app)), `expected ${app} to be removed`).toBe(false);
      }

      // 3. No leftover @monorepo-template scope anywhere.
      const offenders = allFiles(dir).filter((f) => {
        try {
          return readFileSync(f, "utf-8").includes(SCOPE);
        } catch {
          return false;
        }
      });
      expect(offenders.map((f) => path.relative(dir, f))).toEqual([]);

      // 4. Root package.json renamed to the new scope.
      const rootPkg = JSON.parse(readFileSync(path.join(dir, "package.json"), "utf-8"));
      expect(rootPkg.name).toBe("testscope");

      // 5. Generated CI builds this pattern's app.
      const ci = readFileSync(path.join(dir, ".github/workflows/pr-validation.yml"), "utf-8");
      expect(ci).toContain(`working-directory: ${c.ciApp}`);

      // 6. The regenerated architecture doc references no deleted app. Match the
      // path as a whole token so "apps/mobile" does not flag "apps/mobile-convex".
      const arch = readFileSync(path.join(dir, ".claude/architecture.md"), "utf-8");
      for (const app of ALL_APPS) {
        if (c.keep.includes(app)) continue;
        const asToken = new RegExp(`${app.replace("/", "\\/")}(?![\\w-])`);
        expect(asToken.test(arch), `architecture.md still references ${app}`).toBe(false);
      }

      // 7. Dropping mobile must also strip @better-auth/expo from a kept server
      // app — its catalog entry is gone, so a leftover reference breaks install.
      if (!c.mobile) {
        const serverApp = c.keep.find((a) => a.startsWith("apps/server"));
        if (serverApp) {
          for (const rel of ["package.json", "src/lib/auth.ts"]) {
            const contents = readFileSync(path.join(dir, serverApp, rel), "utf-8");
            expect(
              contents,
              `${serverApp}/${rel} still references @better-auth/expo`,
            ).not.toContain("@better-auth/expo");
          }
        }
      }

      // 8. `test:web` filters the web-ui package, so it must survive iff web-ui
      // does — the backend-only pattern drops both.
      const keepsWebUi = existsSync(path.join(dir, "packages/web-ui"));
      expect(Boolean(rootPkg.scripts?.["test:web"]), "test:web vs web-ui presence").toBe(
        keepsWebUi,
      );

      // 9. The integration scripts target the Hono API app, so they survive iff
      // apps/server-hono does.
      const keepsServerHono = existsSync(path.join(dir, "apps/server-hono"));
      expect(
        Boolean(rootPkg.scripts?.["test:integration"]),
        "test:integration vs server-hono presence",
      ).toBe(keepsServerHono);

      // 10. The desktop app is the only consumer of i18n and tokens, so those
      // packages survive exactly when it does — otherwise they are weeds. The
      // backend-only pattern is the documented exception: it keeps i18n for
      // localized email and push copy.
      const keepsDesktop = c.keep.includes("apps/desktop");
      expect(existsSync(path.join(dir, "packages/tokens")), "tokens vs desktop").toBe(keepsDesktop);
      if (c.pattern !== "server-only-hono") {
        expect(existsSync(path.join(dir, "packages/i18n")), "i18n vs desktop").toBe(keepsDesktop);
      }

      // 11. The desktop scripts filter the `desktop` package; a leftover filter
      // matching nothing makes turbo fail.
      for (const script of ["dev:desktop", "test:desktop"]) {
        expect(Boolean(rootPkg.scripts?.[script]), `${script} vs desktop presence`).toBe(
          keepsDesktop,
        );
      }

      // 12. The desktop workflows are committed files, not generated ones, so
      // they have to be deleted by hand when the app goes.
      for (const workflow of [
        ".github/workflows/ci-desktop.yml",
        ".github/workflows/release-desktop.yml",
      ]) {
        expect(existsSync(path.join(dir, workflow)), `${workflow} vs desktop presence`).toBe(
          keepsDesktop,
        );
      }

      // 13. A pattern with nothing to deploy to a Worker must not ship a
      // Cloudflare deploy workflow.
      const deployPath = path.join(dir, ".github/workflows/deploy-production.yml");
      expect(existsSync(deployPath), "deploy-production.yml vs deployable pattern").toBe(
        c.pattern !== "desktop-local-first",
      );
    }, 60_000);
  }
});
